world_address = "0x032c4b5442817f7c7e6c3127dcafd7c5898e97d5f067fd8477437bff3e5bbfd6"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"
start_block = 0
index_pending = false

[database]
db_dir = "./torii_sepolia"

[http]
enabled = true
host = "0.0.0.0"
port = 8080
cors_origins = ["*"]

[grpc]
enabled = true
host = "0.0.0.0"
port = 8081

